import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import DHMLXGanttChart from '../../components/DHMLXGanttChart';
import { gantt } from 'dhtmlx-gantt';
import * as dhtmlxDataConverter from '../../utils/dhtmlxDataConverter';

// モック設定
jest.mock('dhtmlx-gantt');
jest.mock('../../utils/dhtmlxDataConverter');
jest.mock('../../templates/DHMLXCustomBar');
jest.mock('../../hooks/useZoomConfigDHMLX', () => ({
  useZoomConfigDHMLX: () => ({
    level: 'day',
    setLevel: jest.fn(),
    config: { scale_unit: 'day' }
  })
}));

// alertのモック
global.alert = jest.fn();

describe('DHMLXGanttChart - エクスポート機能', () => {
  const mockTasks = [
    {
      id: 1,
      text: 'タスク1',
      start: '2024-01-01',
      end: '2024-01-05',
      progress: 0.5,
      parent: 0,
      editable: true,
      issue_id: '123'
    }
  ];

  const defaultProps = {
    tasks: mockTasks,
    setTasks: jest.fn(),
    links: [],
    visibleColumns: [],
    onColumnSettingsChange: jest.fn(),
    projectId: 'test-project',
    filters: {},
    onFilterChange: jest.fn()
  };

  beforeEach(() => {
    jest.clearAllMocks();
    global.alert.mockClear();
    
    // データ変換モック設定
    dhtmlxDataConverter.convertSvarToGantt.mockImplementation(tasks => 
      tasks.map(task => ({
        ...task,
        start_date: new Date(task.start),
        end_date: new Date(task.end)
      }))
    );
    
    // Ganttモック設定
    gantt.init.mockImplementation(() => {});
    gantt.parse.mockImplementation(() => {});
    gantt.clearAll.mockImplementation(() => {});
    gantt.attachEvent.mockImplementation(() => 1);
    gantt.exportToPDF.mockImplementation(() => {});
    gantt.exportToExcel.mockImplementation(() => {});
    gantt.exportToPNG.mockImplementation(() => {});
    gantt.exportToMSProject.mockImplementation(() => {});
  });

  describe('F005: エクスポート機能', () => {
    it('エクスポートボタンが正しく表示される', () => {
      render(<DHMLXGanttChart {...defaultProps} />);
      
      expect(screen.getByText('📄 PDF')).toBeInTheDocument();
      expect(screen.getByText('📊 Excel')).toBeInTheDocument();
      expect(screen.getByText('🖼️ PNG')).toBeInTheDocument();
      expect(screen.getByText('📋 MS Project')).toBeInTheDocument();
    });

    it('PDFエクスポートが正しく機能する', () => {
      render(<DHMLXGanttChart {...defaultProps} />);
      
      const pdfButton = screen.getByText('📄 PDF');
      fireEvent.click(pdfButton);
      
      expect(gantt.exportToPDF).toHaveBeenCalledWith({
        name: expect.stringMatching(/gantt_chart_\d{4}-\d{2}-\d{2}\.pdf/),
        header: expect.stringContaining('Gantt Chart'),
        footer: expect.stringContaining('Generated by Redmine React Gantt Chart'),
        locale: 'jp',
        raw: true,
        skin: 'dhtmlx_gantt_default'
      });
    });

    it('Excelエクスポートが正しく機能する', () => {
      render(<DHMLXGanttChart {...defaultProps} />);
      
      const excelButton = screen.getByText('📊 Excel');
      fireEvent.click(excelButton);
      
      expect(gantt.exportToExcel).toHaveBeenCalledWith({
        name: expect.stringMatching(/gantt_chart_\d{4}-\d{2}-\d{2}\.xlsx/),
        columns: expect.arrayContaining([
          expect.objectContaining({ id: 'id', header: 'ID' }),
          expect.objectContaining({ id: 'text', header: 'タスク名' }),
          expect.objectContaining({ id: 'tracker_name', header: 'トラッカー' }),
          expect.objectContaining({ id: 'status_name', header: 'ステータス' }),
          expect.objectContaining({ id: 'assigned_to_name', header: '担当者' }),
          expect.objectContaining({ id: 'start_date', header: '開始日' }),
          expect.objectContaining({ id: 'end_date', header: '終了日' }),
          expect.objectContaining({ id: 'duration', header: '期間' }),
          expect.objectContaining({ id: 'progress', header: '進捗' })
        ]),
        visual: true,
        rawDates: false
      });
    });

    it('PNGエクスポートが正しく機能する', () => {
      render(<DHMLXGanttChart {...defaultProps} />);
      
      const pngButton = screen.getByText('🖼️ PNG');
      fireEvent.click(pngButton);
      
      expect(gantt.exportToPNG).toHaveBeenCalledWith({
        name: expect.stringMatching(/gantt_chart_\d{4}-\d{2}-\d{2}\.png/),
        raw: true,
        skin: 'dhtmlx_gantt_default'
      });
    });

    it('MS Projectエクスポートが正しく機能する', () => {
      render(<DHMLXGanttChart {...defaultProps} />);
      
      const msProjectButton = screen.getByText('📋 MS Project');
      fireEvent.click(msProjectButton);
      
      expect(gantt.exportToMSProject).toHaveBeenCalledWith({
        name: expect.stringMatching(/gantt_chart_\d{4}-\d{2}-\d{2}\.xml/),
        project: {
          'Author': 'Redmine React Gantt Chart',
          'Title': 'Project Schedule',
          'Company': 'Your Company'
        }
      });
    });

    it('PDFエクスポートエラー時にアラートが表示される', () => {
      gantt.exportToPDF.mockImplementation(() => {
        throw new Error('PDF export failed');
      });
      
      render(<DHMLXGanttChart {...defaultProps} />);
      
      const pdfButton = screen.getByText('📄 PDF');
      fireEvent.click(pdfButton);
      
      expect(global.alert).toHaveBeenCalledWith('PDFエクスポートに失敗しました。');
    });

    it('Excelエクスポートエラー時にアラートが表示される', () => {
      gantt.exportToExcel.mockImplementation(() => {
        throw new Error('Excel export failed');
      });
      
      render(<DHMLXGanttChart {...defaultProps} />);
      
      const excelButton = screen.getByText('📊 Excel');
      fireEvent.click(excelButton);
      
      expect(global.alert).toHaveBeenCalledWith('Excelエクスポートに失敗しました。');
    });

    it('PNGエクスポートエラー時にアラートが表示される', () => {
      gantt.exportToPNG.mockImplementation(() => {
        throw new Error('PNG export failed');
      });
      
      render(<DHMLXGanttChart {...defaultProps} />);
      
      const pngButton = screen.getByText('🖼️ PNG');
      fireEvent.click(pngButton);
      
      expect(global.alert).toHaveBeenCalledWith('PNGエクスポートに失敗しました。');
    });

    it('MS Projectエクスポートエラー時にアラートが表示される', () => {
      gantt.exportToMSProject.mockImplementation(() => {
        throw new Error('MS Project export failed');
      });
      
      render(<DHMLXGanttChart {...defaultProps} />);
      
      const msProjectButton = screen.getByText('📋 MS Project');
      fireEvent.click(msProjectButton);
      
      expect(global.alert).toHaveBeenCalledWith('MS Projectエクスポートに失敗しました。');
    });

    it('エクスポートファイル名に日付が含まれる', () => {
      const mockDate = new Date('2024-03-15');
      jest.spyOn(Date, 'now').mockReturnValue(mockDate.getTime());
      jest.spyOn(global, 'Date').mockImplementation(() => mockDate);
      
      render(<DHMLXGanttChart {...defaultProps} />);
      
      const pdfButton = screen.getByText('📄 PDF');
      fireEvent.click(pdfButton);
      
      expect(gantt.exportToPDF).toHaveBeenCalledWith(
        expect.objectContaining({
          name: 'gantt_chart_2024-03-15.pdf'
        })
      );
    });

    it('エクスポートボタンにホバースタイルが適用される', () => {
      const { container } = render(<DHMLXGanttChart {...defaultProps} />);
      
      // エクスポートボタンのスタイルが適用されていることを確認
      const exportToolbar = container.querySelector('.export-toolbar');
      expect(exportToolbar).toBeInTheDocument();
      
      const exportButtons = container.querySelectorAll('.export-btn');
      expect(exportButtons).toHaveLength(4);
      
      // 各ボタンのスタイルクラスを確認
      expect(exportButtons[0]).toHaveClass('export-btn-pdf');
      expect(exportButtons[1]).toHaveClass('export-btn-excel');
      expect(exportButtons[2]).toHaveClass('export-btn-png');
      expect(exportButtons[3]).toHaveClass('export-btn-msproject');
    });

    it('エクスポートボタンにツールチップが設定されている', () => {
      render(<DHMLXGanttChart {...defaultProps} />);
      
      const pdfButton = screen.getByText('📄 PDF');
      const excelButton = screen.getByText('📊 Excel');
      const pngButton = screen.getByText('🖼️ PNG');
      const msProjectButton = screen.getByText('📋 MS Project');
      
      expect(pdfButton).toHaveAttribute('title', 'PDFエクスポート');
      expect(excelButton).toHaveAttribute('title', 'Excelエクスポート');
      expect(pngButton).toHaveAttribute('title', 'PNGエクスポート');
      expect(msProjectButton).toHaveAttribute('title', 'MS Projectエクスポート');
    });

    it('エクスポート機能がwindow.ganttApi経由でアクセスできる', () => {
      render(<DHMLXGanttChart {...defaultProps} />);
      
      // window.ganttApiにエクスポート機能が公開されていることを確認
      expect(window.ganttApi).toHaveProperty('exportToPDF');
      expect(window.ganttApi).toHaveProperty('exportToExcel');
      expect(window.ganttApi).toHaveProperty('exportToPNG');
      expect(window.ganttApi).toHaveProperty('exportToMSProject');
      
      // API経由でエクスポートを実行
      window.ganttApi.exportToPDF();
      expect(gantt.exportToPDF).toHaveBeenCalled();
      
      window.ganttApi.exportToExcel();
      expect(gantt.exportToExcel).toHaveBeenCalled();
      
      window.ganttApi.exportToPNG();
      expect(gantt.exportToPNG).toHaveBeenCalled();
      
      window.ganttApi.exportToMSProject();
      expect(gantt.exportToMSProject).toHaveBeenCalled();
    });
  });
});